# Configuración de experimentos con Validación Cruzada
#
# MEJORAS IMPLEMENTADAS PARA RIGOR CIENTÍFICO:
# • K-fold Cross Validation (por defecto k=5)
# • Test set independiente (20% nunca tocado)
# • Estadísticas robustas con intervalos de confianza
# • División estratificada balanceada por clase
# • Métricas agregadas y por fold

experiments:
  # 1. DenseNet121 (3)
  - name: densenet121_lr1e4_bs32
    execute: true
    params:
      model: densenet121
      lr: 1e-4
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10

  - name: densenet121_lr1e5_bs32
    execute: true
    params:
      model: densenet121
      lr: 1e-5
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10

  - name: densenet121_lr1e6_bs32
    execute: true
    params:
      model: densenet121
      lr: 1e-6
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10

  # 2. EfficientNet-B0 (3)
  - name: efficientnet_b0_lr1e4_bs32
    execute: true
    params:
      model: efficientnet_b0
      lr: 1e-4
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10

  - name: efficientnet_b0_lr1e5_bs32
    execute: true
    params:
      model: efficientnet_b0
      lr: 1e-5
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10

  - name: efficientnet_b0_lr1e6_bs32
    execute: true
    params:
      model: efficientnet_b0
      lr: 1e-6
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10

  # 3. MobileNetV2 (3)
  - name: mobilenet_v2_lr1e4_bs32
    execute: true
    params:
      model: mobilenet_v2
      lr: 1e-4
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10

  - name: mobilenet_v2_lr1e5_bs32
    execute: true
    params:
      model: mobilenet_v2
      lr: 1e-5
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10

  - name: mobilenet_v2_lr1e6_bs32
    execute: true
    params:
      model: mobilenet_v2
      lr: 1e-6
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10

  # 4. ResNet50 (3)
  - name: resnet50_lr1e4_bs32
    execute: true
    params:
      model: resnet50
      lr: 1e-4
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10

  - name: resnet50_lr1e5_bs32
    execute: true
    params:
      model: resnet50
      lr: 1e-5
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10

  - name: resnet50_lr1e6_bs32
    execute: true
    params:
      model: resnet50
      lr: 1e-6
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10

  # 5. VGG16 (3)
  - name: vgg16_lr1e4_bs32
    execute: true
    params:
      model: vgg16
      lr: 1e-4
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10

  - name: vgg16_lr1e5_bs32
    execute: true
    params:
      model: vgg16
      lr: 1e-5
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10

  - name: vgg16_lr1e6_bs32
    execute: true
    params:
      model: vgg16
      lr: 1e-6
      epochs: 100
      batch_size: 64
      patience: 5
      k_folds: 10
